local L0_0
L0_0 = string
L0_0 = L0_0.lower
L0_0 = L0_0(mp.IOAVGetDownloadUrl())
if L0_0 ~= nil and string.find(L0_0, "_task=mail&_action=get&_mbox=inbox", 1, true) then
  mp.set_mpattribute("Lua:WebMailDownload")
  if mp.getfilesize() <= 4194304 and (mp.get_mpattribute("Lua:SingleSuspiciousExtensionInZip") or mp.get_mpattribute("Lua:RarHasFileWithExeExtension") or mp.get_mpattribute("Lua:SingleSuspiciousExtensionIn7z") or mp.get_mpattribute("Lua:SingleSuspiciousExtensionInACE")) then
    mp.set_mpattribute("MpForceScanArchives")
  end
  if ({
    [".doc"] = true,
    [".xls"] = true,
    [".rtf"] = true,
    [".docm"] = true,
    [".xlsm"] = true,
    [".ppam"] = true,
    [".pptm"] = true,
    [".ppsm"] = true,
    [".potm"] = true,
    [".xlsx"] = true,
    [".docx"] = true,
    [".jse"] = true,
    [".vbs"] = true,
    [".wsf"] = true,
    [".vbe"] = true,
    [".hta"] = true,
    [".js"] = true,
    [".mht"] = true,
    [".lnk"] = true,
    [".bat"] = true,
    [".ps1"] = true,
    [".zip"] = true,
    [".rar"] = true,
    [".7z"] = true,
    [".iso"] = true,
    [".arj"] = true,
    [".gz"] = true,
    [".ace"] = true,
    [".xz"] = true,
    [".bz"] = true,
    [".r00"] = true,
    [".rev"] = true,
    [".exe"] = true,
    [".scr"] = true,
    [".pif"] = true,
    [".jar"] = true
  })[mp.getfilename(mp.bitor(mp.FILEPATH_QUERY_FNAME, mp.FILEPATH_QUERY_LOWERCASE)):sub(-3)] == true or ({
    [".doc"] = true,
    [".xls"] = true,
    [".rtf"] = true,
    [".docm"] = true,
    [".xlsm"] = true,
    [".ppam"] = true,
    [".pptm"] = true,
    [".ppsm"] = true,
    [".potm"] = true,
    [".xlsx"] = true,
    [".docx"] = true,
    [".jse"] = true,
    [".vbs"] = true,
    [".wsf"] = true,
    [".vbe"] = true,
    [".hta"] = true,
    [".js"] = true,
    [".mht"] = true,
    [".lnk"] = true,
    [".bat"] = true,
    [".ps1"] = true,
    [".zip"] = true,
    [".rar"] = true,
    [".7z"] = true,
    [".iso"] = true,
    [".arj"] = true,
    [".gz"] = true,
    [".ace"] = true,
    [".xz"] = true,
    [".bz"] = true,
    [".r00"] = true,
    [".rev"] = true,
    [".exe"] = true,
    [".scr"] = true,
    [".pif"] = true,
    [".jar"] = true
  })[mp.getfilename(mp.bitor(mp.FILEPATH_QUERY_FNAME, mp.FILEPATH_QUERY_LOWERCASE)):sub(-4)] == true or ({
    [".doc"] = true,
    [".xls"] = true,
    [".rtf"] = true,
    [".docm"] = true,
    [".xlsm"] = true,
    [".ppam"] = true,
    [".pptm"] = true,
    [".ppsm"] = true,
    [".potm"] = true,
    [".xlsx"] = true,
    [".docx"] = true,
    [".jse"] = true,
    [".vbs"] = true,
    [".wsf"] = true,
    [".vbe"] = true,
    [".hta"] = true,
    [".js"] = true,
    [".mht"] = true,
    [".lnk"] = true,
    [".bat"] = true,
    [".ps1"] = true,
    [".zip"] = true,
    [".rar"] = true,
    [".7z"] = true,
    [".iso"] = true,
    [".arj"] = true,
    [".gz"] = true,
    [".ace"] = true,
    [".xz"] = true,
    [".bz"] = true,
    [".r00"] = true,
    [".rev"] = true,
    [".exe"] = true,
    [".scr"] = true,
    [".pif"] = true,
    [".jar"] = true
  })[mp.getfilename(mp.bitor(mp.FILEPATH_QUERY_FNAME, mp.FILEPATH_QUERY_LOWERCASE)):sub(-5)] == true then
    return mp.INFECTED
  end
end
return mp.CLEAN
