if mp.get_contextdata(mp.CONTEXT_DATA_SCANREASON) == mp.SCANREASON_ONOPEN and mp.get_contextdata(mp.CONTEXT_DATA_OPEN_CREATEPROCESS_HINT) then
  if ({
    ["accesschk.exe"] = true,
    ["accesschk64.exe"] = true,
    ["accessenum.exe"] = true,
    ["adexplorer.exe"] = true,
    ["adinsight.exe"] = true,
    ["adrestore.exe"] = true,
    ["autoruns.exe"] = true,
    ["autoruns64.exe"] = true,
    ["autorunsc.exe"] = true,
    ["autorunsc64.exe"] = true,
    ["clockres.exe"] = true,
    ["clockres64.exe"] = true,
    ["contig.exe"] = true,
    ["contig64.exe"] = true,
    ["coreinfo.exe"] = true,
    ["ctrl2cap.exe"] = true,
    ["dbgview.exe"] = true,
    ["disk2vhd.exe"] = true,
    ["diskext.exe"] = true,
    ["diskext64.exe"] = true,
    ["findlinks.exe"] = true,
    ["findlinks64.exe"] = true,
    ["handle.exe"] = true,
    ["handle64.exe"] = true,
    ["hex2dec.exe"] = true,
    ["hex2dec64.exe"] = true,
    ["junction.exe"] = true,
    ["junction64.exe"] = true,
    ["ldmdump.exe"] = true,
    ["livekd.exe"] = true,
    ["livekd64.exe"] = true,
    ["loadord.exe"] = true,
    ["loadord64.exe"] = true,
    ["loadordc.exe"] = true,
    ["loadordc64.exe"] = true,
    ["logonsessions.exe"] = true,
    ["logonsessions64.exe"] = true,
    ["notmyfault.exe"] = true,
    ["notmyfault64.exe"] = true,
    ["notmyfaultc.exe"] = true,
    ["notmyfaultc64.exe"] = true,
    ["ntfsinfo.exe"] = true,
    ["ntfsinfo64.exe"] = true,
    ["pagedfrg.exe"] = true,
    ["pendmoves.exe"] = true,
    ["pendmoves64.exe"] = true,
    ["pipelist.exe"] = true,
    ["pipelist64.exe"] = true,
    ["procdump.exe"] = true,
    ["procdump64.exe"] = true,
    ["procexp.exe"] = true,
    ["procexp64.exe"] = true,
    ["procmon.exe"] = true,
    ["psexec.exe"] = true,
    ["psexec64.exe"] = true,
    ["psfile.exe"] = true,
    ["psfile64.exe"] = true,
    ["psgetsid.exe"] = true,
    ["psgetsid64.exe"] = true,
    ["psinfo.exe"] = true,
    ["psinfo64.exe"] = true,
    ["pskill.exe"] = true,
    ["pskill64.exe"] = true,
    ["pslist.exe"] = true,
    ["pslist64.exe"] = true,
    ["psloggedon.exe"] = true,
    ["psloggedon64.exe"] = true,
    ["psloglist.exe"] = true,
    ["psloglist64.exe"] = true,
    ["pspasswd.exe"] = true,
    ["pspasswd64.exe"] = true,
    ["psping.exe"] = true,
    ["psping64.exe"] = true,
    ["psservice.exe"] = true,
    ["psservice64.exe"] = true,
    ["psshutdown.exe"] = true,
    ["pssuspend.exe"] = true,
    ["pssuspend64.exe"] = true,
    ["rammap.exe"] = true,
    ["regdelnull.exe"] = true,
    ["regdelnull64.exe"] = true,
    ["regjump.exe"] = true,
    ["sdelete.exe"] = true,
    ["sdelete64.exe"] = true,
    ["sigcheck.exe"] = true,
    ["sigcheck64.exe"] = true,
    ["streams.exe"] = true,
    ["streams64.exe"] = true,
    ["sysmon.exe"] = true,
    ["sysmon64.exe"] = true,
    ["tcpvcon.exe"] = true,
    ["tcpview.exe"] = true,
    ["vmmap.exe"] = true,
    ["winobj.exe"] = true
  })[mp.getfilename(mp.bitor(mp.bitor(mp.FILEPATH_QUERY_FNAME, mp.FILEPATH_QUERY_PATH), mp.FILEPATH_QUERY_LOWERCASE))] then
    if mp.IsTrustedFile() then
      return mp.CLEAN
    end
    mp.set_mpattribute("BM_MasqSysinternalUtil")
    return mp.INFECTED
  end
end
return mp.CLEAN
