local L0_0, L1_1
if mp.get_contextdata(mp.CONTEXT_DATA_SCANREASON) == mp.SCANREASON_ONOPEN or mp.get_contextdata(mp.CONTEXT_DATA_SCANREASON) == mp.SCANREASON_ONMODIFIEDHANDLECLOSE then
  L0_0 = mp.get_contextdata(mp.CONTEXT_DATA_FILENAME)
end
if L0_0 == nil then
  L1_1 = string.lower(mp.getfilename())
  if L1_1 == nil then
    return mp.CLEAN
  end
  L0_0 = L1_1:match("([^\\]+)$")
end
if L0_0 ~= nil then
  if string.find(L0_0, "module", 1, true) ~= nil or string.find(L0_0, "option", 1, true) ~= nil or string.find(L0_0, "asyncparser", 1, true) ~= nil or string.find(L0_0, "client", 1, true) ~= nil or string.find(L0_0, "checkout", 1, true) ~= nil or string.find(L0_0, "calendar", 1, true) ~= nil or string.find(L0_0, "fbcontractreviewdetail", 1, true) ~= nil or string.find(L0_0, "animation_", 1, true) ~= nil or string.find(L0_0, "twsc.paypal", 1, true) ~= nil or string.find(L0_0, "jquery", 1, true) ~= nil or string.find(L0_0, "utils", 1, true) ~= nil or string.find(L0_0, "library", 1, true) ~= nil or string.find(L0_0, "helper", 1, true) ~= nil or string.find(L0_0, "registry", 1, true) ~= nil or string.find(L0_0, "view", 1, true) ~= nil or string.find(L0_0, "plusone", 1, true) ~= nil or string.find(L0_0, "mobile", 1, true) ~= nil or string.find(L0_0, "dataviz", 1, true) ~= nil or string.find(L0_0, "abacus", 1, true) ~= nil or string.find(L0_0, "header", 1, true) ~= nil or string.find(L0_0, "tts_web", 1, true) ~= nil or string.find(L0_0, "control", 1, true) ~= nil or string.find(L0_0, "sql", 1, true) ~= nil or string.find(L0_0, "lockbox.", 1, true) ~= nil or string.find(L0_0, "buttons", 1, true) ~= nil or string.find(L0_0, "ajax", 1, true) ~= nil or string.find(L0_0, "applet", 1, true) ~= nil or string.find(L0_0, "edit", 1, true) ~= nil or string.find(L0_0, "rules.", 1, true) ~= nil or string.find(L0_0, "systemtwn", 1, true) ~= nil or string.find(L0_0, "form.", 1, true) ~= nil or string.find(L0_0, ".form", 1, true) ~= nil or string.find(L0_0, "lookup", 1, true) ~= nil or string.find(L0_0, "json", 1, true) ~= nil or string.find(L0_0, "jsp", 1, true) ~= nil or string.find(L0_0, "RecurringPay", 1, true) ~= nil or string.find(L0_0, "aspx", 1, true) ~= nil or string.find(L0_0, "menu", 1, true) ~= nil or string.find(L0_0, "github", 1, true) ~= nil or string.find(L0_0, "accuen", 1, true) ~= nil or string.find(L0_0, "_buyer-protection_", 1, true) ~= nil or string.find(L0_0, "careplanfunction", 1, true) ~= nil or string.find(L0_0, "din_text_payment", 1, true) ~= nil or string.find(L0_0, "dialog", 1, true) ~= nil or string.find(L0_0, "maker", 1, true) ~= nil or string.find(L0_0, "liq.crud", 1, true) ~= nil or string.find(L0_0, "platform", 1, true) ~= nil or string.find(L0_0, "record", 1, true) ~= nil or string.find(L0_0, "skype", 1, true) ~= nil or string.find(L0_0, "query", 1, true) ~= nil or string.find(L0_0, "widget", 1, true) ~= nil or string.find(L0_0, "getshipping", 1, true) ~= nil or string.find(L0_0, "compare-doc", 1, true) ~= nil then
    return mp.CLEAN
  end
  if string.find(L0_0, "boleto", 1, true) ~= nil or string.find(L0_0, "cheque", 1, true) ~= nil or string.find(L0_0, "cobranca", 1, true) ~= nil or string.find(L0_0, "comprovante", 1, true) ~= nil or string.find(L0_0, "deposito", 1, true) ~= nil or string.find(L0_0, "_dhl.js", 1, true) ~= nil or string.find(L0_0, "-dhl.js", 1, true) ~= nil or string.find(L0_0, "dhl_", 1, true) ~= nil or string.find(L0_0, "fattura", 1, true) ~= nil or string.find(L0_0, "fedex", 1, true) ~= nil or string.find(L0_0, "filename_error_id_", 1, true) ~= nil or string.find(L0_0, "_jpg.js", 1, true) ~= nil or string.find(L0_0, ".jpg.js", 1, true) ~= nil or string.find(L0_0, "-jpg.js", 1, true) ~= nil or string.find(L0_0, "orcamento", 1, true) ~= nil or string.find(L0_0, "ordine", 1, true) ~= nil or string.find(L0_0, "_pdf.js", 1, true) ~= nil or string.find(L0_0, ".pdf.js", 1, true) ~= nil or string.find(L0_0, "-pdf.js", 1, true) ~= nil or string.find(L0_0, "_doc.js", 1, true) ~= nil or string.find(L0_0, ".doc.js", 1, true) ~= nil or string.find(L0_0, "-doc.js", 1, true) ~= nil or string.find(L0_0, "purchases_pdf", 1, true) ~= nil or string.find(L0_0, "recibo", 1, true) ~= nil or string.find(L0_0, "unpaid", 1, true) ~= nil or string.find(L0_0, "usps", 1, true) ~= nil or string.find(L0_0, "swift", 1, true) ~= nil or string.find(L0_0, "bradesco", 1, true) ~= nil or string.find(L0_0, "captcha", 1, true) ~= nil or string.find(L0_0, "lordsystem", 1, true) ~= nil or string.find(L0_0, "viagogo", 1, true) ~= nil or string.find(L0_0, "photoshop", 1, true) ~= nil or string.find(L0_0, "exported_bill", 1, true) ~= nil or string.find(L0_0, "export_pdf_", 1, true) ~= nil or string.find(L0_0, "e-bill", 1, true) ~= nil or string.find(L0_0, "notafiscal", 1, true) ~= nil or string.find(L0_0, "faturamento", 1, true) ~= nil or string.find(L0_0, "flash.+player.+upgrade") ~= nil or string.find(L0_0, "addition-%d+%.js") ~= nil or string.find(L0_0, "credit.+report") ~= nil or string.find(L0_0, "delivery.+notification") ~= nil or string.find(L0_0, "label_%d+%.js") ~= nil or string.find(L0_0, "signed doc%d+%.js") ~= nil or string.find(L0_0, "img_%d+%.js") ~= nil or string.find(L0_0, "invoice_%d%d%d%d+_") ~= nil or string.find(L0_0, "quittung..?post") ~= nil or string.find(L0_0, "ffice_equipment_.+%.js") ~= nil then
    return mp.INFECTED
  end
end
return mp.CLEAN
