local L0_0
L0_0 = bm
L0_0 = L0_0.set_scan_param
L0_0(mp.bitor(mp.bitor(bm.SCAN_PARAMETERS_DEEP_ANALYSIS, bm.SCAN_PARAMETERS_VMM_GROW), bm.SCAN_PARAMETERS_HSTR_EXHAUSTIVE))
L0_0 = mp
L0_0 = L0_0.INFECTED
return L0_0
