if not mp.get_mpattribute("PUA:CERT:PCAppStore") then
  return mp.CLEAN
end
if this_sigattrlog[2].matched and this_sigattrlog[4].matched then
  if this_sigattrlog[2].p2 ~= this_sigattrlog[4].p2 and not this_sigattrlog[4].p2:lower():find("pc +app +store +setup$") then
    return mp.CLEAN
  end
  if this_sigattrlog[2].p2:lower():find("^spark +setup$") or this_sigattrlog[2].p2:find("^fast[!]? +setup$") then
    return mp.CLEAN
  end
  for _FORV_7_ = 1, #{
    "^personal +store +setup$",
    "shop +setup$",
    "market +setup$",
    "marketplace +setup$",
    "buy +setup$",
    "baz[a-z]*ar[a-z]* +setup$",
    "sale +setup$",
    "rep +setup$",
    "repository +setup$",
    "soft +setup$",
    "software +setup$",
    "product +setup$",
    "prod +setup$",
    "tool +setup$",
    "package +setup$",
    "platform +setup$",
    "selection +setup$",
    "download +setup$",
    "offer +setup$",
    "item +setup$",
    "data +setup$",
    "element +setup$",
    "property +setup$",
    "thing +setup$",
    "commodity +setup$",
    "^rev +[0-9][0-9][0-9]+[a-z]+ +setup$",
    "^build +[0-9][0-9][0-9]+[a-z]+ +setup$",
    "^bld +[0-9][0-9][0-9]+[a-z]+ +setup$",
    "^[a-z][a-z]? +[0-9][0-9][0-9]+[a-z]* +setup$",
    "^our +setup$",
    "yours +setup$",
    "the +setup$",
    "nice +setup$",
    "because +setup$",
    "just +setup$",
    "bbb +setup$",
    "why +setup$",
    "when +setup$",
    "absolutely +setup$",
    "regards +setup$",
    "flower +setup$",
    "rain +setup$",
    "wind +setup$",
    "earth +setup$",
    "planet +setup$",
    "captain +setup$",
    "mountain +setup$",
    "hill +setup$",
    "foot +setup$",
    "feet +setup$",
    "legs +setup$",
    "hands +setup$",
    "nose +setup$",
    "ears +setup$",
    "chin +setup$",
    "scalp +setup$",
    "magic +setup$",
    "dragon +setup$",
    "ball +setup",
    "hoop +setup$",
    "shins +setup$",
    "sand +setup$",
    "ciao +setup$",
    "foam +setup$",
    "concert +setup$",
    "violin +setup$",
    "happy +setup$",
    "sad +setup$",
    "possibly +setup$",
    "could *be +setup$",
    "morning +setup$",
    "brunch +setup$",
    "dairy +setup$",
    "evening +setup$",
    "farm +setup$",
    "[a-np-z]oo+ +setup$",
    "shed +setup$",
    "unbow +setup$",
    "arch +setup$",
    "medi +setup$",
    "lem +setup$",
    "[b-z]ostan +setup$",
    "[b-z]ur[b-z]ur +setup$",
    "^[a-z][a-z]?[a-z]?[a-z]?[a-z]? +setup$"
  } do
    if this_sigattrlog[2].p2:lower():find(({
      "^personal +store +setup$",
      "shop +setup$",
      "market +setup$",
      "marketplace +setup$",
      "buy +setup$",
      "baz[a-z]*ar[a-z]* +setup$",
      "sale +setup$",
      "rep +setup$",
      "repository +setup$",
      "soft +setup$",
      "software +setup$",
      "product +setup$",
      "prod +setup$",
      "tool +setup$",
      "package +setup$",
      "platform +setup$",
      "selection +setup$",
      "download +setup$",
      "offer +setup$",
      "item +setup$",
      "data +setup$",
      "element +setup$",
      "property +setup$",
      "thing +setup$",
      "commodity +setup$",
      "^rev +[0-9][0-9][0-9]+[a-z]+ +setup$",
      "^build +[0-9][0-9][0-9]+[a-z]+ +setup$",
      "^bld +[0-9][0-9][0-9]+[a-z]+ +setup$",
      "^[a-z][a-z]? +[0-9][0-9][0-9]+[a-z]* +setup$",
      "^our +setup$",
      "yours +setup$",
      "the +setup$",
      "nice +setup$",
      "because +setup$",
      "just +setup$",
      "bbb +setup$",
      "why +setup$",
      "when +setup$",
      "absolutely +setup$",
      "regards +setup$",
      "flower +setup$",
      "rain +setup$",
      "wind +setup$",
      "earth +setup$",
      "planet +setup$",
      "captain +setup$",
      "mountain +setup$",
      "hill +setup$",
      "foot +setup$",
      "feet +setup$",
      "legs +setup$",
      "hands +setup$",
      "nose +setup$",
      "ears +setup$",
      "chin +setup$",
      "scalp +setup$",
      "magic +setup$",
      "dragon +setup$",
      "ball +setup",
      "hoop +setup$",
      "shins +setup$",
      "sand +setup$",
      "ciao +setup$",
      "foam +setup$",
      "concert +setup$",
      "violin +setup$",
      "happy +setup$",
      "sad +setup$",
      "possibly +setup$",
      "could *be +setup$",
      "morning +setup$",
      "brunch +setup$",
      "dairy +setup$",
      "evening +setup$",
      "farm +setup$",
      "[a-np-z]oo+ +setup$",
      "shed +setup$",
      "unbow +setup$",
      "arch +setup$",
      "medi +setup$",
      "lem +setup$",
      "[b-z]ostan +setup$",
      "[b-z]ur[b-z]ur +setup$",
      "^[a-z][a-z]?[a-z]?[a-z]?[a-z]? +setup$"
    })[_FORV_7_]) then
      return mp.INFECTED
    end
  end
end
return mp.CLEAN
