local L0_0, L1_1
function L0_0()
  local L0_2, L1_3
  L0_2 = {}
  L0_2.Name = "Block Adobe Reader from creating child processes"
  L0_2.Description = "Windows Defender Exploit Guard detected Adobe Reader launching child process"
  L0_2.NotificationDedupingInterval = 120
  L1_3 = HIPS
  L1_3 = L1_3.DEDUPE_SCOPE_UI
  L0_2.NotificationDedupingScope = L1_3
  return L0_2
end
GetRuleInfo = L0_0
function L0_0()
  local L0_4, L1_5, L2_6
  L0_4 = {}
  L0_4["%programfiles%\\adobe\\acrobat reader 2015\\reader\\acrord32.exe"] = 2
  L0_4["%programfiles%\\adobe\\acrobat reader 2017\\reader\\acrord32.exe"] = 2
  L0_4["%programfiles%\\adobe\\acrobat reader 2018\\reader\\acrord32.exe"] = 2
  L0_4["%programfiles%\\adobe\\acrobat reader dc\\reader\\acrord32.exe"] = 2
  L0_4["%programfiles%\\adobe\\reader 10.0\\reader\\acrord32.exe"] = 2
  L0_4["%programfiles%\\adobe\\reader 11.0\\reader\\acrord32.exe"] = 2
  L0_4["%programfiles%\\adobe\\reader 8.0\\reader\\acrord32.exe"] = 2
  L0_4["%programfiles%\\adobe\\reader 9.0\\reader\\acrord32.exe"] = 2
  L0_4["%programfiles%\\adobe\\reader\\11.0\\reader\\acrord32.exe"] = 2
  L0_4["%programfiles%\\adobe\\reader\\acrord32.exe"] = 2
  L0_4["%programfiles%\\adobe\\reader\\reader\\acrord32.exe"] = 2
  L0_4["%programfiles(x86)%\\adobe\\acrobat reader 2015\\reader\\acrord32.exe"] = 2
  L0_4["%programfiles(x86)%\\adobe\\acrobat reader 2017\\reader\\acrord32.exe"] = 2
  L0_4["%programfiles(x86)%\\adobe\\acrobat reader 2018\\reader\\acrord32.exe"] = 2
  L0_4["%programfiles(x86)%\\adobe\\acrobat reader dc\\reader\\acrord32.exe"] = 2
  L0_4["%programfiles(x86)%\\adobe\\reader 10.0\\reader\\acrord32.exe"] = 2
  L0_4["%programfiles(x86)%\\adobe\\reader 11.0\\reader\\acrord32.exe"] = 2
  L0_4["%programfiles(x86)%\\adobe\\reader 8.0\\reader\\acrord32.exe"] = 2
  L0_4["%programfiles(x86)%\\adobe\\reader 9.0\\reader\\acrord32.exe"] = 2
  L0_4["%programfiles(x86)%\\adobe\\reader\\11.0\\reader\\acrord32.exe"] = 2
  L0_4["%programfiles(x86)%\\adobe\\reader\\acrord32.exe"] = 2
  L0_4["%programfiles(x86)%\\adobe\\reader\\reader\\acrord32.exe"] = 2
  L0_4["%programfiles%\\adobe\\acrobat 10.0\\acrobat\\acrobat.exe"] = 2
  L0_4["%programfiles%\\adobe\\acrobat 11.0\\acrobat\\acrobat.exe"] = 2
  L0_4["%programfiles%\\adobe\\acrobat 2015\\acrobat\\acrobat.exe"] = 2
  L0_4["%programfiles%\\adobe\\acrobat 2017\\acrobat\\acrobat.exe"] = 2
  L0_4["%programfiles%\\adobe\\acrobat 5.0\\acrobat\\acrobat.exe"] = 2
  L0_4["%programfiles%\\adobe\\acrobat 6.0\\acrobat\\acrobat.exe"] = 2
  L0_4["%programfiles%\\adobe\\acrobat 7.0\\acrobat\\acrobat.exe"] = 2
  L0_4["%programfiles%\\adobe\\acrobat 8.0\\acrobat\\acrobat.exe"] = 2
  L0_4["%programfiles%\\adobe\\acrobat 9.0\\acrobat\\acrobat.exe"] = 2
  L0_4["%programfiles%\\adobe\\acrobat dc\\acrobat\\acrobat.exe"] = 2
  L0_4["%programfiles(x86)%\\adobe\\acrobat 10.0\\acrobat\\acrobat.exe"] = 2
  L0_4["%programfiles(x86)%\\adobe\\acrobat 11.0\\acrobat\\acrobat.exe"] = 2
  L0_4["%programfiles(x86)%\\adobe\\acrobat 2015\\acrobat\\acrobat.exe"] = 2
  L0_4["%programfiles(x86)%\\adobe\\acrobat 2017\\acrobat\\acrobat.exe"] = 2
  L0_4["%programfiles(x86)%\\adobe\\acrobat 5.0\\acrobat\\acrobat.exe"] = 2
  L0_4["%programfiles(x86)%\\adobe\\acrobat 6.0\\acrobat\\acrobat.exe"] = 2
  L0_4["%programfiles(x86)%\\adobe\\acrobat 7.0\\acrobat\\acrobat.exe"] = 2
  L0_4["%programfiles(x86)%\\adobe\\acrobat 8.0\\acrobat\\acrobat.exe"] = 2
  L0_4["%programfiles(x86)%\\adobe\\acrobat 9.0\\acrobat\\acrobat.exe"] = 2
  L0_4["%programfiles(x86)%\\adobe\\acrobat dc\\acrobat\\acrobat.exe"] = 2
  L1_5 = 1
  L2_6 = L0_4
  return L1_5, L2_6
end
GetMonitoredLocations = L0_0
function L0_0()
  local L0_7, L1_8, L2_9
  L0_7 = {}
  L0_7["%commonprogramfiles%\\adobe"] = 2
  L0_7["%commonprogramfiles%\\microsoft shared"] = 2
  L0_7["%commonprogramfiles(x86)%\\adobe"] = 2
  L0_7["%commonprogramfiles(x86)%\\microsoft shared"] = 2
  L0_7["%programdata%\\app-v"] = 2
  L0_7["%programfiles%\\acrobat"] = 2
  L0_7["%programfiles%\\adobe"] = 2
  L0_7["%programfiles%\\firefox developer edition"] = 2
  L0_7["%programfiles%\\foxit software"] = 2
  L0_7["%programfiles%\\google"] = 2
  L0_7["%programfiles%\\internet explorer"] = 2
  L0_7["%programfiles%\\microsoft application virtualization\\client\\subsystems\\appvdllsurrogate32.exe"] = 2
  L0_7["%programfiles%\\microsoft application virtualization\\client\\subsystems\\appvdllsurrogate64.exe"] = 2
  L0_7["%programfiles%\\microsoft office 15"] = 2
  L0_7["%programfiles%\\microsoft office 2003"] = 2
  L0_7["%programfiles%\\microsoft office 2010"] = 2
  L0_7["%programfiles%\\microsoft office 2016"] = 2
  L0_7["%programfiles%\\microsoft office"] = 2
  L0_7["%programfiles%\\microsoft office2003"] = 2
  L0_7["%programfiles%\\microsoft office2007"] = 2
  L0_7["%programfiles%\\microsoft office\\2010"] = 2
  L0_7["%programfiles%\\microsoft office\\live meeting 8"] = 2
  L0_7["%programfiles%\\microsoft office\\office"] = 2
  L0_7["%programfiles%\\microsoft office\\office10"] = 2
  L0_7["%programfiles%\\microsoft office\\office11"] = 2
  L0_7["%programfiles%\\microsoft office\\office12"] = 2
  L0_7["%programfiles%\\microsoft office\\office13"] = 2
  L0_7["%programfiles%\\microsoft office\\office14"] = 2
  L0_7["%programfiles%\\microsoft office\\office15"] = 2
  L0_7["%programfiles%\\microsoft office\\office16"] = 2
  L0_7["%programfiles%\\microsoft office\\root\\2010"] = 2
  L0_7["%programfiles%\\microsoft office\\root\\client\\appvdllsurrogate32.exe"] = 2
  L0_7["%programfiles%\\microsoft office\\root\\client\\appvdllsurrogate64.exe"] = 2
  L0_7["%programfiles%\\microsoft office\\root\\live meeting 8"] = 2
  L0_7["%programfiles%\\microsoft office\\root\\office"] = 2
  L0_7["%programfiles%\\microsoft office\\root\\office10"] = 2
  L0_7["%programfiles%\\microsoft office\\root\\office11"] = 2
  L0_7["%programfiles%\\microsoft office\\root\\office12"] = 2
  L0_7["%programfiles%\\microsoft office\\root\\office13"] = 2
  L0_7["%programfiles%\\microsoft office\\root\\office14"] = 2
  L0_7["%programfiles%\\microsoft office\\root\\office15"] = 2
  L0_7["%programfiles%\\microsoft office\\root\\office16"] = 2
  L0_7["%programfiles%\\microsoft office\\root\\updates"] = 2
  L0_7["%programfiles%\\microsoft office\\root\\vfs"] = 2
  L0_7["%programfiles%\\microsoft office\\root\\visio"] = 2
  L0_7["%programfiles%\\microsoft office\\root\\visio10"] = 2
  L0_7["%programfiles%\\microsoft office\\root\\visio11"] = 2
  L0_7["%programfiles%\\microsoft office\\root\\visio12"] = 2
  L0_7["%programfiles%\\microsoft office\\root\\visio13"] = 2
  L0_7["%programfiles%\\microsoft office\\updates"] = 2
  L0_7["%programfiles%\\microsoft office\\vfs"] = 2
  L0_7["%programfiles%\\microsoft office\\visio"] = 2
  L0_7["%programfiles%\\microsoft office\\visio10"] = 2
  L0_7["%programfiles%\\microsoft office\\visio11"] = 2
  L0_7["%programfiles%\\microsoft office\\visio12"] = 2
  L0_7["%programfiles%\\microsoft office\\visio13"] = 2
  L0_7["%programfiles%\\microsoft security client"] = 2
  L0_7["%programfiles%\\mozilla firefox"] = 2
  L0_7["%programfiles%\\opera"] = 2
  L0_7["%programfiles%\\reader"] = 2
  L0_7["%programfiles%\\sogouinput"] = 2
  L0_7["%programfiles%\\tencent"] = 2
  L0_7["%programfiles%\\ucbrowser"] = 2
  L0_7["%programfiles%\\winrar"] = 2
  L0_7["%programfiles%\\winzip"] = 2
  L0_7["%programfiles%\\Microsoft\\Edge\\Application"] = 2
  L0_7["%programfiles%\\Microsoft\\Edge\\Application\\msedge.exe"] = 2
  L0_7["%programfiles%\\Microsoft\\Edge Dev\\Application\\msedge.exe"] = 2
  L0_7["%programfiles%\\Microsoft\\Edge Beta\\Application\\msedge.exe"] = 2
  L0_7["%programfiles%\\Microsoft\\Edge\\Application\\*\\msedgewebview2.exe"] = 2
  L0_7["%programfiles%\\Microsoft\\Edge Dev\\Application\\*\\msedgewebview2.exe"] = 2
  L0_7["%programfiles%\\Microsoft\\Edge Beta\\Application\\*\\msedgewebview2.exe"] = 2
  L0_7["%programfiles%\\Microsoft\\EdgeWebView\\Application\\*\\msedgewebview2.exe"] = 2
  L0_7["%programfiles%\\AppSense\\Application Manager\\Agent\\AMMessage.exe"] = 2
  L0_7["%programfiles%\\Microsoft OneDrive\\*\\FileCoAuth.exe"] = 2
  L0_7["%programfiles%\\PolicyPak\\Browser Router\\Client\\PPBRAgent.exe"] = 2
  L0_7["%programfiles%\\Nitro\\PDF Pro\\*\\NxPdfCreator.exe"] = 2
  L0_7["%programfiles%\\AnyShare\\sharetool.exe"] = 2
  L0_7["%programfiles%\\PTI\\FusionPro\\ProdReActivate.exe"] = 2
  L0_7["%programfiles%\\Nitro\\PDF Pro\\*\\metrics_tool.exe"] = 2
  L0_7["%programfiles%\\Unify\\Fusion for MS Office\\FusionPlugins\\FusionExecutor.exe"] = 2
  L0_7["%programfiles%\\ELO Digital Office GmbH\\ELO Java Client\\EloActivateJC.exe"] = 2
  L0_7["%programfiles%\\Tracker Software\\PDF-XChange Standard\\pdfSaver.exe"] = 2
  L0_7["%programfiles%\\PDF-XChange\\PDF-XChange Standard\\pdfSaver.exe"] = 2
  L0_7["%programfiles%\\I.CA SecureStore\\IcaCardDialogs\\ICACardDialogs.exe"] = 2
  L0_7["%programfiles%\\BraveSoftware\\Brave-Browser\\Application\\brave.exe"] = 2
  L0_7["%programfiles(x86)%\\acrobat"] = 2
  L0_7["%programfiles(x86)%\\acrobat dc"] = 2
  L0_7["%programfiles(x86)%\\adobe"] = 2
  L0_7["%programfiles(x86)%\\firefox developer edition"] = 2
  L0_7["%programfiles(x86)%\\foxit software"] = 2
  L0_7["%programfiles(x86)%\\google"] = 2
  L0_7["%programfiles(x86)%\\internet explorer"] = 2
  L0_7["%programfiles(x86)%\\microsoft application virtualization\\client\\subsystems\\appvdllsurrogate32.exe"] = 2
  L0_7["%programfiles(x86)%\\microsoft application virtualization\\client\\subsystems\\appvdllsurrogate64.exe"] = 2
  L0_7["%programfiles(x86)%\\microsoft office 15"] = 2
  L0_7["%programfiles(x86)%\\microsoft office 2003"] = 2
  L0_7["%programfiles(x86)%\\microsoft office 2010"] = 2
  L0_7["%programfiles(x86)%\\microsoft office 2016"] = 2
  L0_7["%programfiles(x86)%\\microsoft office"] = 2
  L0_7["%programfiles(x86)%\\microsoft office2003"] = 2
  L0_7["%programfiles(x86)%\\microsoft office2007"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\2010"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\live meeting 8"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\office"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\office10"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\office11"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\office12"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\office13"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\office14"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\office15"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\office16"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\root\\2010"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\root\\client\\appvdllsurrogate32.exe"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\root\\client\\appvdllsurrogate64.exe"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\root\\live meeting 8"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\root\\office"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\root\\office10"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\root\\office11"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\root\\office12"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\root\\office13"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\root\\office14"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\root\\office15"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\root\\office16"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\root\\updates"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\root\\vfs"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\root\\visio"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\root\\visio10"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\root\\visio11"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\root\\visio12"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\root\\visio13"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\updates"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\vfs"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\visio"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\visio10"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\visio11"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\visio12"] = 2
  L0_7["%programfiles(x86)%\\microsoft office\\visio13"] = 2
  L0_7["%programfiles(x86)%\\microsoft security client"] = 2
  L0_7["%programfiles(x86)%\\mozilla firefox"] = 2
  L0_7["%programfiles(x86)%\\opera"] = 2
  L0_7["%programfiles(x86)%\\reader"] = 2
  L0_7["%programfiles(x86)%\\sogouinput"] = 2
  L0_7["%programfiles(x86)%\\tencent"] = 2
  L0_7["%programfiles(x86)%\\ucbrowser"] = 2
  L0_7["%programfiles(x86)%\\winrar"] = 2
  L0_7["%programfiles(x86)%\\winzip"] = 2
  L0_7["%programfiles(x86)%\\Microsoft\\Edge\\Application"] = 2
  L0_7["%programfiles(x86)%\\Microsoft\\Edge\\Application\\msedge.exe"] = 2
  L0_7["%programfiles(x86)%\\Microsoft\\Edge Dev\\Application\\msedge.exe"] = 2
  L0_7["%programfiles(x86)%\\Microsoft\\Edge Beta\\Application\\msedge.exe"] = 2
  L0_7["%programfiles(x86)%\\Microsoft\\Edge\\Application\\*\\msedgewebview2.exe"] = 2
  L0_7["%programfiles(x86)%\\Microsoft\\Edge Dev\\Application\\*\\msedgewebview2.exe"] = 2
  L0_7["%programfiles(x86)%\\Microsoft\\Edge Beta\\Application\\*\\msedgewebview2.exe"] = 2
  L0_7["%programfiles(x86)%\\Microsoft\\EdgeWebView\\Application\\*\\msedgewebview2.exe"] = 2
  L0_7["%programW6432%\\Microsoft\\Edge\\Application\\msedge.exe"] = 2
  L0_7["%programW6432%\\Microsoft\\Edge Dev\\Application\\msedge.exe"] = 2
  L0_7["%programW6432%\\Microsoft\\Edge Beta\\Application\\msedge.exe"] = 2
  L0_7["%programW6432%\\Microsoft\\Edge\\Application\\*\\msedgewebview2.exe"] = 2
  L0_7["%programW6432%\\Microsoft\\Edge Dev\\Application\\*\\msedgewebview2.exe"] = 2
  L0_7["%programW6432%\\Microsoft\\Edge Beta\\Application\\*\\msedgewebview2.exe"] = 2
  L0_7["%programW6432%\\Microsoft\\EdgeWebView\\Application\\*\\msedgewebview2.exe"] = 2
  L0_7["%programfiles(x86)%\\BraveSoftware\\Brave-Browser\\Application\\brave.exe"] = 2
  L0_7["%programfiles(x86)%\\KnowBe4\\Second Chance\\knowbe4.secondchance.userdialog.exe"] = 2
  L0_7["%programfiles(x86)%\\SamsungPrinterLiveUpdateInstaller\\LUMgr.exe"] = 2
  L0_7["%programfiles(x86)%\\Mozilla Thunderbird\\thunderbird.exe"] = 2
  L0_7["%programfiles(x86)%\\Spirion\\IdentityFinderCmd.exe"] = 2
  L0_7["%programfiles(x86)%\\Citrix\\System32\\iexplore.exe"] = 2
  L0_7["%programfiles(x86)%\\Citrix\\HDX\\bin\\iexplore.exe"] = 2
  L0_7["%programfiles(x86)%\\FactSet\\FDSBrowser.exe"] = 2
  L0_7["%programfiles(x86)%\\SHARP\\Printer Status Monitor\\Smon.exe"] = 2
  L0_7["%programfiles(x86)%\\OpenText\\Office Editor\\OTEditTray.exe"] = 2
  L0_7["%programfiles(x86)%\\PTI\\FusionPro\\ProdReActivate.exe"] = 2
  L0_7["%programfiles(x86)%\\NEC\\InfoCageFileShell"] = 2
  L0_7["%programfiles(x86)%\\Nuance\\Power PDF ??\\bin\\SendMail.exe"] = 2
  L0_7["%programfiles(x86)%\\IBM\\Notes\\notes.exe"] = 2
  L0_7["%programfiles(x86)%\\FUJIFILM\\DocumentMonitor\\DocMon\\GetJCID.exe"] = 2
  L0_7["%programfiles(x86)%\\Unify\\Fusion for MS Office\\FusionPlugins\\FusionExecutor.exe"] = 2
  L0_7["%programfiles(x86)%\\Kofax\\*\\bin\\SendMail.exe"] = 2
  L0_7["%programfiles(x86)%\\JustSystems\\ATOK??\\ATFSVR??.EXE"] = 2
  L0_7["%localappdata%\\microsoft\\edge\\application\\msedge.exe"] = 1
  L0_7["%localappdata%\\microsoft\\edge sxs\\application\\msedge.exe"] = 1
  L0_7["%localappdata%\\microsoft\\edge dev\\application\\msedge.exe"] = 1
  L0_7["%localappdata%\\microsoft\\edge beta\\application\\msedge.exe"] = 1
  L0_7["%localappdata%\\microsoft\\edgewebview\\application\\*\\msedgewebview2.exe"] = 1
  L0_7["%localappdata%\\microsoft\\edge sxs\\application\\*\\msedgewebview2.exe"] = 1
  L0_7["%localappdata%\\microsoft\\edge dev\\application\\*\\msedgewebview2.exe"] = 1
  L0_7["%localappdata%\\microsoft\\edge beta\\application\\*\\msedgewebview2.exe"] = 1
  L0_7["%localappdata%\\mozilla firefox\\*\\firefoxportable\\app\\firefox64\\firefox.exe"] = 1
  L0_7["%localappdata%\\mozilla firefox\\firefox.exe"] = 1
  L0_7["%localappdata%\\centbrowser\\application\\chrome.exe"] = 1
  L0_7["%localappdata%\\chromium\\application\\chrome.exe"] = 1
  L0_7["%localappdata%\\epic privacy browser\\application\\epic.exe"] = 1
  L0_7["%localappdata%\\firefox developer edition\\firefox.exe"] = 1
  L0_7["%localappdata%\\google chrome\\*\\googlechromeportable\\app\\chrome-bin\\chrome.exe"] = 1
  L0_7["%localappdata%\\google\\chrome beta\\application\\chrome.exe"] = 1
  L0_7["%localappdata%\\google\\chrome dev\\application\\chrome.exe"] = 1
  L0_7["%localappdata%\\google\\chrome sxs\\application\\chrome.exe"] = 1
  L0_7["%localappdata%\\google\\chrome\\application\\chrome.exe"] = 1
  L0_7["%windir%\\explorer.exe"] = 2
  L0_7["%windir%\\microsoft.net\\framework\\*\\dw20.exe"] = 2
  L0_7["%windir%\\notepad.exe"] = 2
  L0_7["%windir%\\splwow64.exe"] = 2
  L0_7["%windir%\\ssdal.exe"] = 2
  L0_7["%windir%\\SuRun.exe"] = 2
  L0_7["%windir%\\system32\\atbroker.exe"] = 2
  L0_7["%windir%\\system32\\bdeunlock.exe"] = 2
  L0_7["%windir%\\system32\\buaappnt.exe"] = 2
  L0_7["%windir%\\system32\\conhost.exe"] = 2
  L0_7["%windir%\\system32\\ctfmon.exe"] = 2
  L0_7["%windir%\\system32\\dwwin.exe"] = 2
  L0_7["%windir%\\system32\\ie4uinit.exe"] = 2
  L0_7["%windir%\\system32\\igfxem.exe"] = 2
  L0_7["%windir%\\system32\\igfxhk.exe"] = 2
  L0_7["%windir%\\system32\\igfxtray.exe"] = 2
  L0_7["%windir%\\system32\\macromed\\flash\\flashplayerupdateservice.exe"] = 2
  L0_7["%windir%\\system32\\microsoft.uev.synccontroller.exe"] = 2
  L0_7["%windir%\\system32\\notepad.exe"] = 2
  L0_7["%windir%\\system32\\ntprint.exe"] = 2
  L0_7["%windir%\\system32\\pcaui.exe"] = 2
  L0_7["%windir%\\system32\\searchprotocolhost.exe"] = 2
  L0_7["%windir%\\system32\\slui.exe"] = 2
  L0_7["%windir%\\system32\\spool\\drivers"] = 2
  L0_7["%windir%\\system32\\verclsid.exe"] = 2
  L0_7["%windir%\\system32\\werfault.exe"] = 2
  L0_7["%windir%\\system32\\werfaultsecure.exe"] = 2
  L0_7["%windir%\\system32\\wermgr.exe"] = 2
  L0_7["%windir%\\system32\\wevtutil.exe"] = 2
  L0_7["%windir%\\system32\\wfs.exe"] = 2
  L0_7["%windir%\\system32\\xpsrchvw.exe"] = 2
  L0_7["%windir%\\system32\\msiexec.exe"] = 2
  L0_7["%windir%\\system32\\mspaint.exe"] = 2
  L0_7["%windir%\\system32\\BuCAppNT.exe"] = 2
  L0_7["%windir%\\system32\\BuMAppNT.exe"] = 2
  L0_7["%windir%\\syswow64\\config\\systemprofile\\sogouinput\\*\\sgtool.exe"] = 2
  L0_7["%windir%\\syswow64\\ctfmon.exe"] = 2
  L0_7["%windir%\\syswow64\\dwwin.exe"] = 2
  L0_7["%windir%\\syswow64\\ieunatt.exe"] = 2
  L0_7["%windir%\\syswow64\\ime\\imejp\\imjpdct.exe"] = 2
  L0_7["%windir%\\syswow64\\ime\\shared\\imecfmui.exe"] = 2
  L0_7["%windir%\\syswow64\\ime\\shared\\imepadsv.exe"] = 2
  L0_7["%windir%\\syswow64\\macromed\\flash\\flashplayerupdateservice.exe"] = 2
  L0_7["%windir%\\syswow64\\mspaint.exe"] = 2
  L0_7["%windir%\\syswow64\\notepad.exe"] = 2
  L0_7["%windir%\\syswow64\\openwith.exe"] = 2
  L0_7["%windir%\\syswow64\\prevhost.exe"] = 2
  L0_7["%windir%\\syswow64\\verclsid.exe"] = 2
  L0_7["%windir%\\syswow64\\werfault.exe"] = 2
  L0_7["%windir%\\syswow64\\wermgr.exe"] = 2
  L0_7["%windir%\\syswow64\\xpsrchvw.exe"] = 2
  L0_7["%windir%\\syswow64\\msiexec.exe"] = 2
  L0_7["%windir%\\syswow64\\launchwinapp.exe"] = 2
  L0_7["%windir%\\systemapps\\*\\microsoftedgecp.exe"] = 2
  L1_8 = 2
  L0_7["%windir%\\winsxs\\*\\iexplore.exe"] = L1_8
  L1_8 = "%windir%\\winsxs\\*\\splwow64.exe"
  L2_9 = 2
  L0_7[L1_8] = L2_9
  L1_8 = "%windir%\\winsxs\\*\\werfault.exe"
  L2_9 = 2
  L0_7[L1_8] = L2_9
  L1_8 = "%windir%\\system32\\fsiso.exe"
  L2_9 = 2
  L0_7[L1_8] = L2_9
  L1_8 = "%userprofile%\\appdata\\local\\google\\chrome"
  L2_9 = 1
  L0_7[L1_8] = L2_9
  L1_8 = "%userprofile%\\appdata\\local\\microsoft\\onedrive"
  L2_9 = 1
  L0_7[L1_8] = L2_9
  L1_8 = "%userprofile%\\appdata\\locallow\\copitrak"
  L2_9 = 1
  L0_7[L1_8] = L2_9
  L1_8 = "%userprofile%\\appdata\\local\\centbrowser\\application\\chrome.exe"
  L2_9 = 1
  L0_7[L1_8] = L2_9
  L1_8 = "%userprofile%\\appdata\\local\\microsoft\\edge\\application\\msedge.exe"
  L2_9 = 1
  L0_7[L1_8] = L2_9
  L1_8 = "%userprofile%\\appdata\\local\\microsoft\\edge sxs\\application\\msedge.exe"
  L2_9 = 1
  L0_7[L1_8] = L2_9
  L1_8 = "%userprofile%\\appdata\\local\\microsoft\\edge dev\\application\\msedge.exe"
  L2_9 = 1
  L0_7[L1_8] = L2_9
  L1_8 = "%userprofile%\\appdata\\local\\microsoft\\edge beta\\application\\msedge.exe"
  L2_9 = 1
  L0_7[L1_8] = L2_9
  L1_8 = "%userprofile%\\appdata\\local\\microsoft\\edgewebview\\application\\*\\msedgewebview2.exe"
  L2_9 = 1
  L0_7[L1_8] = L2_9
  L1_8 = "%userprofile%\\appdata\\local\\microsoft\\edge sxs\\application\\*\\msedgewebview2.exe"
  L2_9 = 1
  L0_7[L1_8] = L2_9
  L1_8 = "%userprofile%\\appdata\\local\\microsoft\\edge dev\\application\\*\\msedgewebview2.exe"
  L2_9 = 1
  L0_7[L1_8] = L2_9
  L1_8 = "%userprofile%\\appdata\\local\\microsoft\\edge beta\\application\\*\\msedgewebview2.exe"
  L2_9 = 1
  L0_7[L1_8] = L2_9
  L1_8 = "%userprofile%\\appdata\\local\\mozilla firefox\\*\\firefoxportable\\app\\firefox64\\firefox.exe"
  L2_9 = 1
  L0_7[L1_8] = L2_9
  L1_8 = "%userprofile%\\appdata\\local\\mozilla firefox\\firefox.exe"
  L2_9 = 1
  L0_7[L1_8] = L2_9
  L1_8 = "%userprofile%\\appdata\\local\\packages\\*\\localcache\\local\\google\\chrome\\application\\chrome.exe"
  L2_9 = 1
  L0_7[L1_8] = L2_9
  L1_8 = "%userprofile%\\appdata\\local\\packages\\*\\localcache\\local\\mozilla firefox\\firefox.exe"
  L2_9 = 1
  L0_7[L1_8] = L2_9
  return L0_7
end
GetPathExclusions = L0_0
function L0_0()
  return {
    ["\\\"?rundll32(\\.exe)?\\\"?\\s+\\\"?.:\\\\windows\\\\system32\\\\spool\\\\drivers\\\\x64\\\\\\d+\\\\hpmsn\\d+\\.dll\\\"?,monitorprintjobstatus\\s+/pjob=\\d+\\s+/pname"] = 0
  }
end
GetCommandLineExclusions = L0_0
